### ISSUE TITLE
Where is `python-daemons` used?

### ISSUE THREAD

**Issue by ayushpriya10** [mzfr/liffy#3]
The module `python-daemons` defined under requirements.txt doesn't seem to be used and trying to install it with pip throws an error.

**Comment by mzfr** [comment]
The `python-daemons` module is used in [core/Server.py](https://github.com/mzfr/liffy/blob/master/core/Server.py)

Also, the error was caused because I misspelled the name in requirements.txt
I have fixed the issue in 43a92981de236f90f55e6666dc86e2013611bd3d

Thanks for reporting this.

**Comment by ayushpriya10** [comment]
My bad. I went back and saw the import line.

Thanks for the help and swift correction!
